export const makeMovie = (overrides: Partial<Movie> = {}): Movie => ({
  movie: "Test Movie",
  jh_score: 75,
  genre: "Action",
  year: 2020,
  ranking: "1",
  plot: "",
  poster: "https://image.tmdb.org/t/p/w500/test.jpg",
  cast: [],
  directors: [],
  ratings: [],
  boxoffice: "",
  rated: "",
  runtime: 120,
  provider: { link: "", rent: [], flatrate: [], buy: [] },
  budget: "",
  tmdbid: 1,
  recommendations: [],
  rottentomatoes: "",
  imdb: "",
  metacritic: "",
  trailer: "",
  dani_approved: false,
  ...overrides,
});

export const makeTmdbMovie = (
  overrides: Partial<TMDBMovie> = {},
): TMDBMovie => ({
  adult: false,
  backdrop_path: "",
  genre_ids: [],
  id: 99,
  original_language: "en",
  original_title: "TMDB Movie",
  overview: "",
  popularity: 0,
  poster_path: "/tmdb.jpg",
  release_date: "2024-01-01",
  title: "TMDB Movie",
  video: false,
  vote_average: 0,
  vote_count: 0,
  ...overrides,
});
